source 'https://api.berkshelf.com'

metadata

cookbook 'cb-common',
         git: 'git@github.com:frkline/cb-common.git',
         branch: 'release-0.3.0',
         rel: 'cookbook'
cookbook 'java_ext',
         git: 'git@github.com:frkline/java_ext.git',
         tag: '0.1.1'
