name 'cb-java'
maintainer 'Frank Kline'
maintainer_email 'frank.kline@gmail.com'
license 'All rights reserved'
description 'Installs/Configures cb-java'
long_description 'Installs/Configures cb-java'
version '0.1.0'

depends 'cb-common', '= 0.3.0'
depends 'java', '= 1.22.0'
depends 'java_ext', '= 0.1.1'
